language: java

jdk:
  openjdk13

after_success:
  bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      g1377@protonmail.com
    on_success: never
    on_failure: always

env:
  global:
    CODECOV_TOKEN="a84e8928-2f62-4127-8435-27ece167ff51"